version: "3"
volumes:
  db:
services:
  mongo:
    image: mongo
    volumes:
      - "db:/data/db"
    ports:
      - "${MONGO_PORT}:27017"
  parse-server:
    build: "../parse-server"
    environment:
      - PARSE_SERVER_APPLICATION_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_SERVER_MASTER_KEY=${PARSE_SERVER_MASTER_KEY}
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo/test
    ports:
      - "${PARSE_SERVER_PORT}:1337"
    depends_on:
      - mongo
  parse-dashboard:
    build: "../parse-dashboard"
    ports:
      - "${PARSE_DASHBOARD_PORT}:4040"
    environment:
      - PARSE_DASHBOARD_USER_ID=${PARSE_DASHBOARD_USER_ID}
      - PARSE_DASHBOARD_USER_PASSWORD=${PARSE_DASHBOARD_USER_PASSWORD}
      - PARSE_DASHBOARD_APP_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_DASHBOARD_MASTER_KEY=${PARSE_SERVER_MASTER_KEY}
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:${PARSE_SERVER_PORT}/parse
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
  